# UniMediTrend AI
## Data Generation and Database Setup

## Installing dependecies

In [7]:
# Force Jupyter to reload imported modules automatically
%load_ext autoreload
%autoreload 2
    
from pymongo import MongoClient
from generate_dataset import generate_dataset

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [8]:
#dataset loading
df = generate_dataset()
df.head()

,visit_date,level,gender,department,hostel,diagnosis,severity
0,2024-01-15,200,Male,Electrical & Electronic Engineering,Gold Refinery Hall,Physical Injury,1
1,2024-01-15,400,Female,Electrical & Electronic Engineering,The Point Hostel,Stress/Fatigue,3
2,2024-01-15,400,Female,Computer Science & Engineering,Castle Gate,Food Poisoning,2
3,2024-01-15,200,Male,Mining Engineering,Kabi's Hostel,Physical Injury,3
4,2024-01-15,300,Male,Mining Engineering,Gold Refinery Hall,Stress/Fatigue,1

In [9]:
print(f"Records: {len(df):,}")
print(f"Date range: {df['visit_date'].min().date()} → {df['visit_date'].max().date()}")
print(df.dtypes)

Records: 5,799
Date range: 2024-01-15 → 2026-03-31
visit_date    datetime64[us]
level                  int64
gender                   str
department               str
hostel                   str
diagnosis                str
severity               int64
dtype: object

In [10]:
# 1. Initialize connection
client = MongoClient('mongodb://localhost:27017/')
db = client['UniMediTrend']
collection = db['clinic_logs']

# 2. Idempotency Check: Clear the collection to prevent duplicates
collection.delete_many({})
print("Cleared existing records in 'clinic_logs'...")

# 3. Convert the pandas DataFrame to BSON format
records = df.to_dict('records')

# 4. THE FIX: Assign the insert operation to a variable named 'result'
# This traps the massive list of ObjectIds inside the variable so they don't print!
result = collection.insert_many(records)

# 5. Verify the insertion cleanly
print(f"Success! {collection.count_documents({})} records securely loaded into the 'UniMediTrend' database.")

Cleared existing records in 'clinic_logs'...
Success! 5799 records securely loaded into the 'UniMediTrend' database.

In [11]:
df.head()

,visit_date,level,gender,department,hostel,diagnosis,severity
0,2024-01-15,200,Male,Electrical & Electronic Engineering,Gold Refinery Hall,Physical Injury,1
1,2024-01-15,400,Female,Electrical & Electronic Engineering,The Point Hostel,Stress/Fatigue,3
2,2024-01-15,400,Female,Computer Science & Engineering,Castle Gate,Food Poisoning,2
3,2024-01-15,200,Male,Mining Engineering,Kabi's Hostel,Physical Injury,3
4,2024-01-15,300,Male,Mining Engineering,Gold Refinery Hall,Stress/Fatigue,1

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5799 entries, 0 to 5798
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   visit_date  5799 non-null   datetime64[us]
 1   level       5799 non-null   int64
 2   gender      5799 non-null   str
 3   department  5799 non-null   str
 4   hostel      5799 non-null   str
 5   diagnosis   5799 non-null   str
 6   severity    5799 non-null   int64
dtypes: datetime64[us](1), int64(2), str(4)
memory usage: 608.8 KB

: